name: AWS OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: readx

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_TO_ASSUME}}
          aws-region: ${{vars.AWS_REGION}}
          role-session-name: My-Session
          role-duration-seconds: 10800  #3hours and updated the role's Maximum session duration to 4 hours in IAM in AWS Console

      - name: Verify AWS identity
        run: aws sts get-caller-identity
